bot/urls.py
from django.urls import path
from .views_folder import unavailable_products_view, order_summary_view, tip_summary_view, table_summary_view

urlpatterns = [
    path('api/order_summary/', order_summary_view.api_order_summary, name='api_order_summary'),
    path('api/tip_summary/', tip_summary_view.api_tip_summary, name='api_tip_summary'),
    path('api/table_summary/', table_summary_view.api_table_summary, name='api_table_summary'),
    path('api/unavailable_products/', unavailable_products_view.api_unavailable_products, name='api_unavailable_products'),
]

pickup_app/urls.py
from django.urls import path


from pickup_app.pickup_views.pickup_menu_view import pickup_menu_view
from pickup_app.pickup_views.pickup_create_view import pickup_create_view
from pickup_app.pickup_views.pdf_template_view import pickup_pdf_template_view
from pickup_app.pickup_views.pickup_pdf_views import pickup_generate_pdf_view
from pickup_app.pickup_views.pickup_search_view import pickup_search_products_view
from pickup_app.pickup_views.pickup_kitchen_template_view import pickup_kitchen_view, print_kitchen

from pickup_app.pickup_views.pickup_cart_view import (
    pickup_cart_view, 
    pickup_add_to_cart_view, 
    pickup_remove_product_view,
    pickup_increase_product_view,
    pickup_decrease_product_view,
    pickup_total_price_view,
    pickup_empty_cart_view
                                          
)


app_name = 'pickup_app'

urlpatterns = [
    path('', pickup_create_view, name='pickup_create'),
    path('pickup_search/<str:phone_number>/', pickup_search_products_view, name='pickup_search_products'),

    path('pickup_empty_cart/<str:phone_number>/', pickup_empty_cart_view, name='pickup_empty_cart'),

    path('pickup_cart/<str:phone_number>/<str:category>/', pickup_cart_view, name='pickup_cart'),
    path('pickup_menu/<str:phone_number>/<str:category>/', pickup_menu_view, name='pickup_menu'),
    path('pickup_total_price/<str:phone_number>/', pickup_total_price_view, name='pickup_total_price'),
    path('pickup_add_to_cart/<str:phone_number>/<int:product_id>/<str:category>/', pickup_add_to_cart_view, name='pickup_add_to_cart'),

    path('pickup_kitchen_template/<str:phone_number>/<int:order_id>/', pickup_kitchen_view, name='pickup_kitchen_template'),

    path('print_kitchen/', print_kitchen, name='print_kitchen'),

    path('pickup_generate_pdf/<str:phone_number>/<int:order_id>/', pickup_generate_pdf_view, name='pickup_generate_pdf'),

    path('pickup_pdf_template/<str:phone_number>/<int:order_id>/', pickup_pdf_template_view, name='pickup_pdf_template'),

    path('pickup_remove_product/<str:phone_number>/<int:product_id>/', pickup_remove_product_view, name='pickup_remove_product'), 
    path('pickup_increase_product/<str:phone_number>/<int:product_id>/', pickup_increase_product_view, name='pickup_increase_product'),
    path('pickup_decrease_product/<str:phone_number>/<int:product_id>/', pickup_decrease_product_view, name='pickup_decrease_product'),
] 

pickup_app/models.py
from django.db import models
from django.utils import timezone
from django.db.models import Sum

from restaurant_app.models.product import Product


class PickupOrder(models.Model):
    phone = models.CharField(max_length=20)
    name = models.CharField(max_length=20)
    date_created = models.DateTimeField(auto_now_add=True, editable=False)
    date_updated = models.DateTimeField(auto_now=True, editable=False)
    is_completed = models.BooleanField(default=False)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    payment_method = models.CharField(max_length=20, blank=True, null=True)
    cart_snapshot = models.TextField(blank=True, null=True)
    transaction_created = models.BooleanField(default=False)
    
    NEW = 'new'
    PROCESSING = 'processing'
    COMPLETED = 'completed'
    CANCELED = 'canceled'

    STATUS_CHOICES = [
        (NEW, 'New'),
        (PROCESSING, 'Processing'),
        (COMPLETED, 'Completed'),
        (CANCELED, 'Canceled'),
    ]

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=NEW)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f"{self.phone} ({self.name})"
    
    def previous_orders_total(self):
        total = PickupOrder.objects.filter(phone=self.phone, date_created__lt=self.date_created).aggregate(Sum('total_amount'))['total_amount__sum'] or 0
        return total

class Cart(models.Model):
    pickup_order = models.ForeignKey(PickupOrder, on_delete=models.CASCADE, related_name='carts')
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    total_price = models.DecimalField(max_digits=8, decimal_places=2, default=0)

    def get_total(self):
        if not self.pk:  # check if the object has been saved to the database
            return 0
        else:
            return sum([item.quantity * item.product.product_price for item in self.cart_items.all()])

    def save(self, *args, **kwargs):
        self.total_price = self.get_total()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Cart ({self.pk}) for {self.pickup_order.phone}"

class OrderItem(models.Model):
    order = models.ForeignKey(PickupOrder, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="cart_items")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    printed_quantity = models.PositiveIntegerField(default=0)  # добавлено это поле

    def __str__(self):
        return f"{self.quantity} x {self.product.product_name_rus}"



pickup_app/forms.py
from django import forms

from .models import PickupOrder
from restaurant_app.models.orders import OrderItem

class PickupForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PickupForm, self).__init__(*args, **kwargs)
        self.fields['name'].required = False
        
        # Устанавливаем стили для полей
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control form-control-lg'
            field.widget.attrs['style'] = 'width: 300px;'
        
        # Дополнительные стили для конкретных полей
        self.fields['phone'].widget.attrs['style'] += 'width: 300px;'
        self.fields['name'].widget.attrs['style'] += 'width: 300px;'

    class Meta:
        model = PickupOrder
        fields = ['phone', 'name']
        labels = {
            'phone': 'Номер телефона:',
            'name': 'Имя:',
        }

class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['product', 'quantity', 'phone_number']


class ProductQuantityForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=10000, initial=1, widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'style': 'width: 100px; display: inline-block;'
    }))

class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Поиск'}))

pickup_app/templates/pickup_cart.html
{% extends "base.html" %}
{% load custom_tags %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

{% block title %}Информация о заказе на Самовывоз{% endblock %}

{% block content %}
<div class="container">
    <div class="my-4">
        <a href="{% url 'pickup_app:pickup_menu' phone_number=pickup_order.phone category='salads' %}" type="submit" class="btn btn-primary">Меню</a>
    </div>
    <h1 class="my-4" style="color: white;">Информация о заказе на Самовывоз</h1>
    <p style="color: white; font-size: 20px;">Номер Телефона: {{ pickup_order.phone }}</p>
    <table class="table">
        <thead>
            <tr>
                <th scope="col" style="color: white; font-size: 26px; text-align: center;">Название</th>
                <th scope="col" style="color: white; font-size: 26px; text-align: center;">Количество</th>
                <th scope="col" style="color: white; font-size: 26px; text-align: center;">Цена</th>
                <th scope="col" style="color: white; font-size: 26px; text-align: center;">Действия</th>
            </tr>
        </thead>
        <tbody>
          {% for item in cart_items %}
<tr>
    <td style="color: rgb(231, 235, 5); text-align: center; vertical-align: middle;">{{ item.product.product_name_rus }}</td>
    <td id="order-item-{{ item.id }}-quantity" style="color: white; text-align: center; vertical-align: middle;">{{ item.quantity|append_grams:item.product.product_name_rus }}</td>
    <td style="color: rgb(255, 255, 255); text-align: center; vertical-align: middle;">{{ item.product.product_price }}₪</td>
    <td style="text-align: center; vertical-align: middle;">
        <div class="btn-group" role="group">
            <button type="button" class="btn1" onclick="event.preventDefault(); document.getElementById('increase-form-{{ item.id }}').submit();">Добавить</button>
            <form id="increase-form-{{ item.id }}" method="POST" action="{% url 'pickup_app:pickup_increase_product' pickup_order.phone item.product.id %}" style="display: none;">
                {% csrf_token %}
                <input type="hidden" name="product_id" value="{{ item.product.id }}">
            </form>
            <button type="button" class="btn1" onclick="event.preventDefault(); document.getElementById('decrease-form-{{ item.id }}').submit();">Убавить</button>
            <form id="decrease-form-{{ item.id }}" method="POST" action="{% url 'pickup_app:pickup_decrease_product' pickup_order.phone item.product.id %}" style="display: none;">
                {% csrf_token %}
                <input type="hidden" name="product_id" value="{{ item.product.id }}">
            </form>
            <button type="button" class="btn1" onclick="event.preventDefault(); document.getElementById('remove-form-{{ item.id }}').submit();">Удалить</button>
            <form id="remove-form-{{ item.id }}" method="POST" action="{% url 'pickup_app:pickup_remove_product' pickup_order.phone item.product.id %}" style="display: none;">
                {% csrf_token %}
                <input type="hidden" name="product_id" value="{{ item.product.id }}">
            </form>
        </div>
    </td>
</tr>
{% endfor %}

          
        </tbody>
    </table>

    <p style="color: white;">Общая сумма: {{ cart|pickup_total_price }}₪</p>

<div class="payment-section mx-auto d-flex flex-column align-items-center">
  <form id="payment-form" method="post" action="{% url 'pickup_app:pickup_generate_pdf' phone_number=pickup_order.phone order_id=pickup_order.id %}">
    <label class="form-group" style="color: rgb(238, 4, 4); font-size: 26px; text-align: center; display: block;">Метод Оплаты:</label>
    <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="payment_method" id="cash" value="cash">
          <label class="form-check-label mr-3" for="cash" style="color: rgb(238, 4, 4);">
              Наличные
          </label>
      </div>
      <div class="form-check mb-2">
          <input class="form-check-input" type="radio" name="payment_method" id="card" value="card">
          <label class="form-check-label mr-3" for="card" style="color: rgb(238, 4, 4);">
              Кредитная карта
          </label>
      </div>
      {% csrf_token %}
      <div class="d-flex justify-content-between">
          <button type="submit" id="pay-button" name="pay-button" value="aaa" class="btn2 btn-primary2 mr-3">Счет Оплачен.</button>
          <button type="button" id="print-kitchen" name="print-kitchen" class="btn-primary2 mr-3">Подтвердить Заказ.</button>
          <button type="button" id="print-bill" name="print-bill" class="btn-primary2" value="Распечатать Счет." onclick="printInvoice('{{ pickup_order.phone }}', '{{ pickup_order.id }}')">Распечатать Счет.</button>
      </div>
  </form>
</div>
</div>
    

<script src="https://unpkg.com/htmx.org/dist/htmx.min.js"></script>

<script>
    var cashInput = document.getElementById('cash');
    var creditCardInput = document.getElementById('card');
    var payButton = document.getElementById('pay-button');

    cashInput.addEventListener('change', handlePaymentMethodChange);
    creditCardInput.addEventListener('change', handlePaymentMethodChange);

    function handlePaymentMethodChange() {
        payButton.removeAttribute('disabled');
    }

    payButton.addEventListener('click', function(event) {
        var paymentMethod = document.querySelector('input[name="payment_method"]:checked');
        if (!paymentMethod) {
            alert('Выберите способ оплаты!');
            event.preventDefault();
        }
    });
</script>

<script>
function printInvoice(phoneNumber, orderId) {
  var printWindow = window.open('', '', 'height=600,width=800,hidden');

  fetch(`/pickup/pickup_pdf_template/${phoneNumber}/${orderId}/`, {
    method: 'GET',
    headers: {'X-Requested-With': 'XMLHttpRequest'}
  })
  .then(response => response.text())
  .then(html => {
    printWindow.document.write(html);
    setTimeout(function() {
      printWindow.print();
      setTimeout(function() {
        printWindow.close();
      }, 1);
    }, 50);
    printWindow.onbeforeunload = function() {
      printWindow.close();
    };
  }); 
}
</script>

<script>
  document.getElementById('print-kitchen').addEventListener('click', function() {
      var phone = '{{ pickup_order.phone }}';
      var orderId = '{{ pickup_order.id }}';
      var xhr = new XMLHttpRequest();
      xhr.open('GET', '{% url "pickup_app:print_kitchen" %}?phone_number=' + phone + '&order_id=' + orderId);
      xhr.onload = function() {
          if (xhr.status === 200) {
              var response = JSON.parse(xhr.responseText);
              alert(response.message);
          }
      };
      xhr.send();
  });
</script>
{% endblock %}

pickup_app/templates/pickup_create.html
{% extends "base.html" %}

{% block title %}Создать заказ на самовывоз{% endblock %}

{% block content %}
<h1 class="mb-4" style="color: white;">Создать заказ на самовывоз</h1>
<form method="POST" action="{% url 'pickup_app:pickup_create' %}">
    {% csrf_token %}
    <input type="hidden" name="phone_number" value="{{ phone_number }}">
    <div class="form-group">
        {% for field in form %}
        <label for="{{ field.id_for_label }}" style="color: white;">{{ field.label }}</label>
        {{ field }}
        {% endfor %}
    </div>

    <button type="submit" class="btn btn-primary">Подвердить</button>
</form>
{% endblock %}

pickup_app/templates/pickup_empty_cart.html
{% extends "base.html" %}
{% load custom_tags %}

{% block title %}Информация о заказе{% endblock %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
{% block content %}
<div class="container">


  <h1 class="my-4" style="color: white;">Нет товаров для №: {{ phone_number }}</h1>


  <h1 class="my-4" style="color: white; font-size: 30px;">
    для того чтоб добавить товар вернитесь <a href="{% url 'pickup_app:pickup_menu' phone_number=phone_number category='salads' %}" type="submit" class="btn btn-primary">Меню</a>
  </h1>

{% endblock %}
        

pickup_app/templates/pickup_kitchen_template.html
<!doctype html>
{% load custom_tags %}
<html dir="rtl">
<head>
    <style>
        h1,h2,h3,h4 {
        text-align: center;
        }
        p {
        text-align: center;
        }
        th, td {
        text-align: center;
        }
    </style>
  <meta charset="utf-8">
  <div stryle="text-align: center">
    <div id="print-area">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
  
</head>
<body>
  <h3>доставка</h3>
  <table>
    <tbody>
      {% for item in cart_items %}
        {% with allowed_categories="salads,meat_dishes" %}
          {% if item.product.category in allowed_categories %}
            {% with restricted_salads="Лобио,Аджапсандал" %}
              {% with restricted_salads_list=restricted_salads|split:"," %}
                {% if item.product.category != "salads" or item.product.name not in restricted_salads_list %}
                  {% if forloop.first %}
                    </tbody>
                  </table>
                  <table>
                    <thead>
                      <tr>
                        <th>Количество</th>
                        <th>Продукт</th>
                      </tr>
                    </thead>
                    <tbody>
                  {% endif %}
                  <tr>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.product_id|get_product_name_rus }}</td>
                  </tr>
                  {% if forloop.last %}
                    </tbody>
                  </table>
                  {% endif %}
                {% endif %}
              {% endwith %}
            {% endwith %}
          {% endif %}
        {% endwith %}
      {% endfor %}
  <style>
    table {
      width: 100%;
      
    }
    
    th, td {
      padding: 8px;
      text-align: right;
      
    }
    </style>
</div>
</body>
</html>

pickup_app/templates/pickup_menu.html
{% extends "base.html" %}
{% load static %}
{% block title %}Меню{% endblock %}
<script src="https://unpkg.com/htmx.org/dist/htmx.min.js"></script>
<script src="{% static 'scripts/search.js' %}"></script>

{% block content %}
<div class="container">
    {% if pickup_order.phone %}
    <div class="my-4">
        <a href="{% url 'pickup_app:pickup_cart' phone_number=pickup_order.phone category=category %}" type="submit" class="btn btn-primary">Корзина</a>
    </div>
    {% endif %}
    <h1 class="my-4" style="color: white;">Меню на Самовывоз №: {{ phone_number }}</h1>
    <section>
        {% include 'pickup_search.html' %}
    </section>
    <ul class="nav nav-tabs mb-4">
        {% for key, value in CATEGORIES.items %}
            {% if key == "soft_drinks" %}
                </ul>
                <ul class="nav nav-tabs mb-4">
            {% endif %}
            <li class="nav-item">
                <a href="{% url 'pickup_app:pickup_menu' phone_number=phone_number category=key %}" class="nav-link pickup-nav-link{% if category == key %} active{% endif %}">{{ value }}</a>

            </li>
        {% endfor %}
    </ul>    

    <div id="products-container" class="row" hx-target="#products-container">
        {% for product in products %}
        <div class="col-md-3 mb-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ product.product_name_rus }}</h5>
                    <p class="card-text">{{ product.product_price }}₪</p>
                    <form action="{% url 'pickup_app:pickup_add_to_cart' phone_number=phone_number product_id=product.id category=category %}" method="POST">
                        {% csrf_token %}
                        {{ product_quantity_form.quantity }}
                        <input type="hidden" name="product_id" value="{{ product.id }}">
                        <button type="submit" class="btn btn-primary" {% if not product.is_available %}disabled{% endif %}>Добавить в корзину</button>
                        {% if not product.is_available %}
                            <p>Продукт закончился</p>
                        {% endif %}
                        {% if product.has_limit %}
                            <p>Осталось: {{ product.limit_quantity }}</p>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

pickup_app/templates/pickup_pdf_template.html
<!doctype html>
{% load custom_tags %}
<html dir="rtl">
<head>
    <style>
        h1,h2,h3,h4 {
        text-align: center;
        }
        p {
        text-align: center;
        }
        th, td {
        text-align: center;
        }
    </style>
  <meta charset="utf-8">
  <div stryle="text-align: center">
    <div id="print-area">
    <h1>MIMINO georgian khachapuri</h1>
    <p>---------------------------------</p>
    <p>שד׳ בן גוריון 15, חיפה</p>
    <p>טלפון: 04-8113399</p>
    <p>ע.מ: 515695377</p>
    <p>שם לקוח: לקוח כללי</p>
    <p>---------------------------------</p>
  </div>  
  <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
  
</head>
<body>
  <h3>מס טלפון: {{ order }}</h3>
  <table>
    <tbody>
      {% for item in cart_items %}
        {% if forloop.first %}
        </tbody>
      </table>
      <table>
        <thead>
          <tr>
            <th>מחיר</th>
            <th>כמות</th>
            <th>מוצר</th>
          </tr>
        </thead>
        <tbody>
        {% endif %}
        <tr>
          <td>{{ item.product.product_price }}₪</td>
          <td>{{ item.quantity }}</td>
          <td>{{ item.product_id|get_product_name_heb }}</td>
        </tr>
        {% if forloop.last %}
      </tbody>
    </table>
    {% endif %}
  {% endfor %}
  <style>
    table {
      width: 100%;
      
    }
    
    th, td {
      padding: 8px;
      text-align: right;
      
    }
    </style>
  <h3>סה"כ: {{ total_price }}₪ </h3>
  <p>תודה על ההזמנה </p>
</div>
</body>
</html>

pickup_app/templates/pickup_search.html
<script src="https://unpkg.com/htmx.org/dist/htmx.min.js"></script>


  <form method="GET" 
  id="search-form" 
  class="flex items-center rounded-md border border-gray-200" 
  hx-get="{% url 'pickup_app:pickup_search_products' phone_number=phone_number %}" 
  hx-target="#search_results">


    <input type="text" 
    name="q" 
    class="py-2 px-4 text-gray-700 leading-tight focus:outline-none" 
    placeholder="Искать Продукт" 
    hx-swap="outerHTML"  
    hx-trigger="keyup changed delay:500">
    <button type="submit" 
    class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-md">
      Искать
    </button>
  </form>
  
  <div id="search_results"></div>

pickup_app/templates/pickup_search_results.html
{% block content %}
  <h2 style="color: white;">То что получилось найти по запросу:"{{ query }}"</h2>
  
  {% if products %}
    <ul>
      {% for product in products %}
        <li style="color: white;">
          <div style="display: flex; align-items: center;">
            <div style="flex: 1;">
              <h5 class="card-title">{{ product.product_name_rus }}, {{ product.product_price }}₪</h5>
            </div>
            <div style="margin-left: 10px;">
              <form action="{% url 'pickup_app:pickup_add_to_cart' phone_number=phone_number product_id=product.id category=category %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="product_id" value="{{ product.id }}">
                <input type="hidden" name="user_phone" value="{{ request.user.phone }}">
                {{ product_quantity_form.as_p }}
                <button type="submit" class="btn btn-primary">Добавить в корзину</button>
              </form>
            </div>
          </div>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p style="color: white;">Ничего не найдено по запросу.</p>
  {% endif %}
{% endblock %}