bot/urls.py
from django.urls import path
from .views_folder import unavailable_products_view, order_summary_view, tip_summary_view, table_summary_view

urlpatterns = [
    path('api/order_summary/', order_summary_view.api_order_summary, name='api_order_summary'),
    path('api/tip_summary/', tip_summary_view.api_tip_summary, name='api_tip_summary'),
    path('api/table_summary/', table_summary_view.api_table_summary, name='api_table_summary'),
    path('api/unavailable_products/', unavailable_products_view.api_unavailable_products, name='api_unavailable_products'),
]

order_statistics/urls.py
from django.urls import path
from .views import daily_orders

app_name = 'order_statistics'

urlpatterns = [
    path('daily-orders/', daily_orders, name='daily-orders'),
]

order_statistics/models.py
from django.db import models
from django.utils import timezone
from restaurant_app.models.tables import Table
from restaurant_app.models.product import Product
from django.contrib.auth.models import User

class StatisticsOrder(models.Model):
    table = models.ForeignKey(Table, on_delete=models.CASCADE, related_name='statistics_orders')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='statistics_orders')
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    is_completed = models.BooleanField(default=False)
    comments = models.TextField(null=True, blank=True)
    last_printed_comments = models.TextField(null=True, blank=True)
    table_number = models.IntegerField()
    total_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    status = models.CharField(max_length=20)
    payment_method = models.CharField(max_length=10, null=True, blank=True)

    class Meta:
        managed = False
        db_table = 'restaurant_app_order'

class StatisticsOrderItem(models.Model):
    order = models.ForeignKey(StatisticsOrder, on_delete=models.CASCADE, related_name='statistics_order_items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='statistics_order_items')
    quantity = models.PositiveIntegerField(default=1)
    phone_number = models.CharField(max_length=10)
    printed = models.BooleanField(default=False)
    printed_quantity = models.IntegerField(default=0)

    class Meta:
        managed = False
        db_table = 'restaurant_app_orderitem'
    
    def __str__(self):
        return f"OrderItem {self.pk} ({self.product})" 
    

restaurant_app/models/message.py
from django.db import models
from django.contrib.auth.models import User

class Chat(models.Model):
    participants = models.ManyToManyField(User, related_name='chats')
    created_at = models.DateTimeField(auto_now_add=True)

    @classmethod
    def get_default_chat(cls):
        default_chat, created = cls.objects.get_or_create(id=1, defaults={})
        return default_chat.id

class Message(models.Model):
    chat = models.ForeignKey(Chat, related_name='messages', on_delete=models.CASCADE)
    sender = models.ForeignKey(User, related_name='sent_messages', on_delete=models.CASCADE)
    body = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    class Meta:
        ordering = ['-timestamp']

    @classmethod
    def unread_count(cls, user):
        return cls.objects.filter(chat__participants=user, read=False).count()

restaurant_app/models/product.py
from django.db import models
from django import forms
from django.conf import settings
from django.urls import reverse

class Product(models.Model):
    CATEGORY_CHOICES = [
        ('first_dishes', 'first_dishes'),
        ('meat_dishes', 'meat_dishes'),
        ('bakery', 'bakery'),
        ('khinkali', 'khinkali'),
        ('khachapuri', 'khachapuri'),
        ('garnish', 'garnish'),
        ('grill_meat', 'grill_meat'),
        ('dessert', 'dessert'),
        ('soups', 'soups'),
        ('salads', 'salads'),
        ('sales', 'sales'),
        ('delivery', 'delivery'),
        ('drinks', 'drinks'),
        ('soft_drinks', 'soft_drinks'),
        ('beer', 'beer'),
        ('wine', 'wine'),
        ('vodka', 'vodka'),
        ('cognac', 'cognac'),
        ('whisky', 'whisky'),
        ('dessert_drinks', 'dessert_drinks'),
        ('own_alc', 'own_alc'),
        ('banket', 'banket'),
        ('mishloha', 'mishloha'),
    ]

    PRINTER_CHOICES = [
        ('print80', 'Бар'),
        ('Printer80', 'Мал Кухня'),
        ('Printer80-2', 'Бол Кухня'),
    ]

    id = models.AutoField(primary_key=True)
    product_name_rus = models.CharField(max_length=100, verbose_name='Название блюда (рус.)')
    product_name_heb = models.CharField(max_length=100, verbose_name='שם מנה (עברית)')
    product_price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='Цена продукта')
    product_img = models.ImageField(upload_to='product_images/', blank=True, null=True)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    printer = models.CharField(max_length=50, choices=PRINTER_CHOICES, default='print80', verbose_name='Принтер')
    created_at = models.DateTimeField(auto_now_add=True)
    quantity = models.PositiveIntegerField(default=1)
    delivery_price = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)
    is_available = models.BooleanField(default=True)
    preparation_time = models.PositiveIntegerField(default=0, verbose_name='Время приготовления (в минутах)', blank=True)
    has_limit = models.BooleanField(default=False, verbose_name='Лимитированный продукт')
    limit_quantity = models.PositiveIntegerField(null=True, blank=True, verbose_name='Количество лимита')
    is_available_for_delivery = models.BooleanField(default=False, verbose_name='Доступен для доставки')
    show_in_menu = models.BooleanField(default=True, verbose_name='Показывать в меню')

    def __str__(self):
        return f"{self.product_name_rus} ({self.product_price}₪)"
    
    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'pk': self.pk})


class ProductQuantityForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['quantity']


class OrderChangeLog(models.Model):
    ACTION_CHOICES = (
        ('add', 'Добавили'),
        ('decrease', 'Убавили'),
        ('delete', 'Удалили'),
        ('increase', 'Прибавили'),
    )

    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    order_item = models.ForeignKey('OrderItem', on_delete=models.CASCADE, null=True, blank=True)
    product_name = models.CharField(max_length=255)
    action = models.CharField(max_length=10, choices=ACTION_CHOICES)
    change_time = models.DateTimeField(auto_now_add=True)
    changed_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='Изменил')

    class Meta:
        ordering = ['change_time']


class ProductStock(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='stock')
    received_quantity = models.PositiveIntegerField()
    received_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.product.product_name_rus} - {self.received_quantity} received on {self.received_date}"

restaurant_app/models/tables.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from django.conf import settings

class Room(models.Model):
    name = models.CharField(max_length=255)
    max_capacity = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


class Table(models.Model):
    table_id = models.IntegerField()
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='tables', null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    is_booked = models.BooleanField(default=False)
    is_ordered = models.BooleanField(default=False)
    reserved_date = models.DateField(null=True, blank=True)
    reserved_time = models.TimeField(null=True, blank=True)
    num_of_people = models.IntegerField(null=True, blank=True)
    order_time = models.DateTimeField(null=True, blank=True)
    are_guests_here = models.BooleanField(default=False)
    capacity = models.IntegerField()
    active_order = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)  # Новый атрибут

    def get_active_order(self):
        from .orders import Order  # Импортируем модель Order внутри метода, чтобы избежать цикличного импорта
        return Order.objects.filter(table=self, is_completed=False).last()

    def __str__(self):
        return f'Table {self.table_id}'

    def orders(self):
        from .orders import Order
        return Order.objects.filter(table=self)

    class Meta:
        ordering = ['table_id']


class VirtualTable(models.Model):
    main_table = models.ForeignKey(Table, related_name='virtual_tables', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    is_closed = models.BooleanField(default=False)

    def __str__(self):
        return f"VirtualTable for Table {self.main_table.table_id} (ID: {self.id})"


class Booking(models.Model):
    table = models.ForeignKey(Table, on_delete=models.CASCADE, related_name='bookings')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bookings')
    reserved_date = models.DateField()
    reserved_time = models.TimeField()
    num_of_people = models.IntegerField()
    are_guests_here = models.BooleanField(default=False)
    description = models.TextField(blank=True, null=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    guests_did_not_arrive = models.BooleanField(default=False)

    def __str__(self):
        return f"Бронирование {self.id} - стол {self.table.table_id} ({self.reserved_date} {self.reserved_time} {self.user.first_name})"


class GuestsHereForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['are_guests_here']
        widgets = {'are_guests_here': forms.HiddenInput()}


class Tip(models.Model):
    amount = models.DecimalField(max_digits=6, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True, db_index=True)  # Добавление индекса
    order = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='tips', null=True, blank=True)

    def __str__(self):
        return f"Total tip: {self.amount} on {self.date}"


class TipDistribution(models.Model):
    tip = models.ForeignKey(Tip, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        unique_together = (('tip', 'user'),)
        indexes = [
            models.Index(fields=['user', 'amount'])  # Добавление индекса
        ]

    def __str__(self):
        return f"{self.user.username} получает {self.amount} чаевых от чаевых {self.tip.id}"


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='userprofile')
    tips = models.FloatField(default=0)


class TipGoal(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='tipgoal')
    goal = models.FloatField(default=0)

order_statistics/views.py
from django.http import JsonResponse
from .models import get_daily_orders

def daily_orders(request):
    data = get_daily_orders()
    return JsonResponse(list(data), safe=False)

restaurant_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from django.contrib.auth.decorators import login_required

from .models.tables import Table, Booking
from .models.orders import Order, OrderItem
from .models.product import Product

from .forms import GuestsHereForm, BookingForm
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.utils import timezone

@login_required
def book_table_view(request):
    if request.method == 'POST':
        form = BookingForm(request.POST, request=request)
        if form.is_valid():
            booking = form.save(commit=False)  # Создаем объект бронирования, но пока не сохраняем в базе данных
            booking.user = request.user

            # Теперь используем выбранный стол из очищенных данных формы
            selected_table = form.cleaned_data.get('table')
            if selected_table:
                booking.table = selected_table  # Устанавливаем выбранный стол
            else:
                # Обработка случая, если подходящий стол не был найден (можно добавить сообщение об ошибке)
                messages.error(request, 'Подходящий стол не найден.')
                return render(request, 'book_table.html', {'form': form})

            booking.save()  # Сохраняем объект бронирования в базе данных
            # ... остальная логика ...
            return redirect('ask_where')
    else:
        form = BookingForm(request=request)
    
    return render(request, 'book_table.html', {'form': form})



@login_required
def bookings_view(request):
    # Получаем текущую дату
    today = timezone.now().date()

    # Получаем и сортируем бронирования начиная с ближайшей даты к текущей
    bookings = Booking.objects.filter(reserved_date__gte=today, is_deleted=False).order_by('reserved_date', 'reserved_time')

    context = {'bookings': bookings}
    return render(request, 'bookings.html', context)

@login_required
def guests_here_view(request, booking_id):
    booking = get_object_or_404(Booking, id=booking_id)
    if request.method == 'POST':
        form = GuestsHereForm(request.POST, instance=booking)
        if form.is_valid():
            booking = form.save(commit=False)
            booking.are_guests_here = not booking.are_guests_here
            booking.user = request.user
            if booking.are_guests_here:
                booking.table.is_booked = False
                booking.table.are_guests_here = True
                booking.table.save()
                booking.is_deleted = True
            booking.save()
            messages.success(request, 'Статус гостей обновлен.')
            return redirect('bookings')
    else:
        form = GuestsHereForm(instance=booking, initial={'are_guests_here': booking.are_guests_here})
    return render(request, 'guests_here.html', {'form': form, 'booking': booking})

@login_required
def start_order_view(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.order_time = timezone.now()  # Update order_time field to current time
    order.save()
    return redirect('order_detail', order_id=order_id)




restaurant_app/templates/book_table.html
{% extends "base.html" %}
{% load static %}
{% block title %}Забронировать стол{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<div class="container">
    <a href="{% url 'rooms' %}" class="btn btn-primary">Назад.</a>
    <h1 style="color: white; font-size: 32px;">Забронировать стол</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Забронировать</button>
        </div>
    </form>
</div>
{% endblock %}

restaurant_app/templates/cart_detail.html
{% extends "base_cart.html" %}
{% load custom_tags %}
{% load static %}

{% block order_header %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<div class="container">
    <div class="my-4 d-flex justify-content-between align-items-center">
        <div class="d-flex justify-content-center flex-grow-1">
            <a href="{% url 'menu' table_id=order.table.table_id category='salads' %}" class="btn btn-primary mx-2">Меню</a>
            <a href="{% url 'room_detail' room_id=table.room.id %}" class="btn btn-primary mx-2">Комната</a>
        </div>
        <div class="d-flex justify-content-end flex-shrink-0">
            <a href="{% url 'split_order' order.id %}" class="btn btn-secondary">Разделить счет</a>
        </div>
    </div>
    <h1 class="my-4" style="color: white;">Информация о заказе</h1>
    <p style="color: white; font-size: 20px;">Номер стола: {{ order.table.table_id }}</p>
</div>
{% endblock order_header %}

{% block order_items %}
{% csrf_token %}
{% for order_item in order.order_items.all %}
<tr>
    <td>
        {% for log in order_logs %}
            {% if log.product_name == order_item.product.product_name_rus %}
            <div style="color: white;">
                {{ log.change_time|date:"H:i" }} - {{ log.get_action_display }}
            </div>
            {% endif %}
        {% endfor %}
    </td>
    
    <td>
        <form class="form-with-checkbox" method="POST" action="{% url 'update_delivery_status' order_item.id %}">
            {% csrf_token %}
            <input type="checkbox" class="big-checkbox no-box-shadow" name="is_delivered" onchange="this.form.submit()" {% if order_item.is_delivered %} checked {% endif %}>
        </form>
    </td>     
    <td style="color: rgb(231, 235, 5);">{{ order_item.product.product_name_rus }}</td>
    <td id="order-item-{{ order_item.id }}-quantity" style="color: white;">{{ order_item.quantity|append_grams:order_item.product.product_name_rus }}</td>
    <td style="color: rgb(255, 255, 255);">{{ order_item.product.product_price }}₪</td>
    <td class="product-quantity">
        <button type="button" class="btn1" onclick="event.preventDefault(); document.getElementById('add-form-{{ order_item.id }}').submit();">Добавить</button>
        <form id="add-form-{{ order_item.id }}" method="POST" action="{% url 'increase_product_in_order' order.id order_item.id %}" style="display: none;">
            {% csrf_token %}
            <input type="hidden" name="product_id" value="{{ order_item.product.id }}">
        </form>
        <button type="button" class="btn1" onclick="location.href='{% url 'password_check' order.id 'decrease' order_item.id %}'">Убавить</button>
        <button type="button" class="btn1" onclick="location.href='{% url 'password_check' order.id 'delete' order_item.id %}'">Удалить</button>
    </td>
</tr>
{% endfor %}
{% endblock order_items %}

{% block payment_method %}
<form id="payment-form" method="post" action="{% url 'cart_detail' order.id %}">
    {% csrf_token %}
    <label class="form-group" style="color: rgb(238, 4, 4); font-size: 26px;">Метод Оплаты:</label>
    <div id="split-payment-inputs" style="display: none;">
        <input type="number" name="cash_amount" id="cash-amount" placeholder="Сумма Наличкой" oninput="checkPaymentSum()" />
        <input type="number" name="card_amount" id="card-amount" placeholder="Сумма Картой" oninput="checkPaymentSum()" />
    </div>
    <div class="d-flex align-items-center mb-2">
        <div class="text-left mr-2">
            <input type="checkbox" id="split-payment" name="split_payment" onchange="toggleSplitPayment()" />
            <label for="split-payment" style="color: rgb(238, 4, 4);">Разделить платеж</label>
        </div>
        <div class="form-check text-left mr-2">
            <input class="form-check-input" type="radio" name="payment_method" id="cash" value="cash" onchange="toggleSplitPayment(false)">
            <label class="form-check-label" for="cash" style="color: rgb(238, 4, 4);">
                Наличные
            </label>
        </div>
        <div class="form-check text-left">
            <input class="form-check-input" type="radio" name="payment_method" id="credit_card" value="card" onchange="toggleSplitPayment(false)">
            <label class="form-check-label" for="credit_card" style="color: rgb(238, 4, 4);">
                Кредитная карта
            </label>
        </div>
    </div>

    <div class="d-flex flex-row mb-2">
        <button type="submit" id="pay-button" class="btn btn-primary mr-2">Оплатить</button>
        <button type="button" id="print-kitchen" name="print-kitchen" class="btn btn-primary mr-2">Подтвердить Заказ</button>
        <button type="button" class="btn btn-primary" id="print-button">Загрузка...</button>
    </div>
</form>

<!-- Отображение частичных платежей и оставшейся суммы -->
<div id="partial-payment-info">
    <p style="color: white; font-size: 18px;">
        Наличные: {{ partial_cash }}₪ <br>
        Картой: {{ partial_card }}₪ <br>
        Осталось заплатить: {{ remaining_total }}₪
    </p>
</div>
{% endblock payment_method %}

<!-- Добавление формы для закрытия стола -->
{% block close_table %}
<form method="post" action="{% url 'close_table_view' %}">
    {% csrf_token %}
    <input type="hidden" name="table_id" value="{{ order.table.table_id }}">
    <button type="submit" class="btn btn-primary">Закрыть стол</button>
</form>
{% endblock close_table %}

{% block script %}
<script src="{% static 'scripts/cart_detail.js' %}"></script>
<script>
    function sendLinkToPaul(orderId) {
        fetch('/send-link-to-paul/', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}',
            },
            body: JSON.stringify({ order_id: orderId })
        })
        .then(response => {
            if (response.ok) {
                alert('Просьба об распечате счета отправлена.');
            } else {
                alert('Ошибка при отправке ссылки.');
            }
        })
        .catch(error => console.error('Ошибка:', error));
    }

    var orderId = '{{ order.id }}';
    var printKitchenUrl = '{% url "print_kitchen" %}';
    var remainingTotal = {{ remaining_total|floatformat:2 }};

    document.addEventListener('DOMContentLoaded', function() {
        var paymentMethodInputs = document.querySelectorAll('input[name="payment_method"]');
        var payButton = document.getElementById('pay-button');
        var printButton = document.getElementById('print-button');
        var tableId = '{{ order.table.table_id }}';

        // Определяем, является ли устройство настольным компьютером или мобильным устройством/планшетом
        var isDesktop = !/Mobi|Android/i.test(navigator.userAgent);

        if (isDesktop) {
            printButton.textContent = 'Распечатать счет';
            printButton.onclick = function() {
                printInvoice(orderId);
            };
        } else {
            printButton.textContent = 'Послать на печать';
            printButton.onclick = function() {
                sendLinkToPaul(orderId);
            };
        }

        function checkPaymentMethod() {
            var isPaymentMethodSelected = Array.from(paymentMethodInputs).some(input => input.checked);
            payButton.disabled = !isPaymentMethodSelected;
        }

        paymentMethodInputs.forEach(function(input) {
            input.addEventListener('change', checkPaymentMethod);
        });

        checkPaymentMethod(); 
    });

    function toggleSplitPayment(isSplit = true) {
        var splitPaymentInputs = document.getElementById('split-payment-inputs');
        var partialPaymentInfo = document.getElementById('partial-payment-info');
        var splitPaymentChecked = document.getElementById('split-payment').checked;

        splitPaymentInputs.style.display = isSplit && splitPaymentChecked ? 'block' : 'none';
        partialPaymentInfo.style.display = isSplit && splitPaymentChecked ? 'block' : 'none';
    }

    function checkPaymentSum() {
        var cashAmount = parseFloat(document.getElementById('cash-amount').value) || 0;
        var cardAmount = parseFloat(document.getElementById('card-amount').value) || 0;
        var totalPayment = cashAmount + cardAmount;
        var partialPaymentInfo = document.getElementById('partial-payment-info');

        if (totalPayment < remainingTotal) {
            partialPaymentInfo.innerHTML = `
                <p style="color: white; font-size: 18px;">
                    Наличные: ${cashAmount}₪ <br>
                    Картой: ${cardAmount}₪ <br>
                    Осталось заплатить: ${remainingTotal - totalPayment}₪
                </p>`;
            partialPaymentInfo.style.display = 'block';
        } else {
            partialPaymentInfo.style.display = 'none';
        }
    }
</script>
<style>
    .big-checkbox {
        transform: scale(1.5);
    }
    form .big-checkbox {
        background: transparent; 
        border: none; 
    }
    td form {
        background: transparent; 
        display: flex; 
        justify-content: center; 
        align-items: center; 
    }
    td form .big-checkbox {
        background: transparent; 
        border: none; 
        flex-shrink: 0; 
    }
    td .form-with-checkbox {
        display: flex; 
        justify-content: center; 
        align-items: center; 
        height: 100%; 
        background: transparent; 
        margin: 0; 
    }
    td .form-with-checkbox .big-checkbox {
        transform: scale(1.5); 
        background: transparent; 
        border: none; 
        flex-shrink: 0; 
    }
</style>
{% endblock script %}

restaurant_app/templates/chat_detail.html
{% extends 'base.html' %}

{% block title %}Чат{% endblock %}

{% block content %}
<h1>Чат с {% for user in chat.participants.all %}{{ user.username }}{% if not forloop.last %}, {% endif %}{% endfor %}</h1>

<div id="unread-messages-count" class="unread-messages-count">
    Непрочитанные сообщения: <span id="unread-count">0</span>
</div>

<form id="delete-messages-form" method="post" action="{% url 'delete_selected_messages' chat.id %}">
    {% csrf_token %}
    <div id="chat-log" class="chat-log">
        <ul class="messages">
            {% for message in messages_received %}
                <li class="message {% if message.sender == request.user %}sent{% else %}received{% endif %}">
                    <div class="message-info">
                        <span class="sender">{{ message.sender.username }}</span>
                        <span class="timestamp">{{ message.timestamp|date:"F j, Y, g:i a" }}</span>
                        <input type="checkbox" name="messages" value="{{ message.id }}" class="message-checkbox">
                    </div>
                    <div class="message-body">{{ message.body }}</div>
                </li>
            {% empty %}
                <li class="no-messages">Сообщений нет.</li>
            {% endfor %}
        </ul>
    </div>
    {% if messages_received %}
        <button type="submit" class="btn btn-danger">Удалить выбранные</button>
    {% endif %}
</form>
<form id="chat-message-form" method="post" action="{% url 'chat_detail' chat.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Отправить сообщение</button>
</form>

<form id="delete-all-messages-form" method="post" action="{% url 'delete_all_messages' chat.id %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить все сообщения</button>
</form>

{% endblock %}

{% block extra_js %}
<script>
    const chatId = "{{ chat.id }}";
    const username = "{{ request.user.username }}";

    const chatSocket = new WebSocket(
        'ws://' + window.location.host + '/ws/chat/' + chatId + '/'
    );

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        const message = data.message;
        const sender = data.sender;
        const timestamp = data.timestamp;

        const messageElement = document.createElement('li');
        messageElement.className = 'message';
        if (sender === username) {
            messageElement.classList.add('sent');
        } else {
            messageElement.classList.add('received');
        }
        messageElement.innerHTML = `
            <div class="message-info">
                <span class="sender">${sender}</span>
                <span class="timestamp">${timestamp}</span>
                <input type="checkbox" name="messages" value="${data.id}" class="message-checkbox">
                <button type="button" class="btn btn-danger btn-sm delete-message" data-message-id="${data.id}">Удалить</button>
            </div>
            <div class="message-body">${message}</div>
        `;
        document.querySelector('.messages').appendChild(messageElement);

        // Обновление счетчика непрочитанных сообщений
        updateUnreadCount();
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-form').onsubmit = function(e) {
        e.preventDefault();

        const messageInputDom = document.querySelector('#id_body');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message,
            'sender': username
        }));
        messageInputDom.value = '';
    };

    document.querySelectorAll('.delete-message').forEach(button => {
        button.addEventListener('click', function() {
            const messageId = this.dataset.messageId;
            fetch(`/delete_message/${messageId}/`, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
                }
            }).then(response => {
                if (response.ok) {
                    this.closest('.message').remove();
                }
            });
        });
    });

    function updateUnreadCount() {
        fetch('/unread_messages_count/')
            .then(response => response.json())
            .then(data => {
                document.getElementById('unread-count').textContent = data.unread_messages_count;
            });
    }

    // Инициализация счетчика непрочитанных сообщений
    updateUnreadCount();
</script>
{% endblock %}

<style>
.unread-messages-count {
    font-weight: bold;
    margin-bottom: 10px;
}

.chat-log {
    max-height: 500px;
    overflow-y: scroll;
    border: 1px solid #ccc;
    padding: 10px;
    margin-bottom: 20px;
    background-color: #f9f9f9;
}

.messages {
    list-style: none;
    padding: 0;
    display: flex;
    flex-direction: column;
}

.message {
    margin-bottom: 10px;
    padding: 10px;
    border-radius: 10px;
    max-width: 60%;
    display: flex;
    flex-direction: column;
}

.message.sent {
    align-self: flex-end;
    background-color: #dcf8c6;
    text-align: right;
}

.message.received {
    align-self: flex-start;
    background-color: #f1f0f0;
    text-align: left;
}

.message-info {
    font-size: 0.8em;
    color: #555;
    display: flex;
    justify-content: space-between;
    margin-bottom: 5px;
}

.message-body {
    font-size: 1em;
}

.sender {
    font-weight: bold;
}

.timestamp {
    font-style: italic;
}

.delete-message {
    color: red;
    margin-left: 10px;
    cursor: pointer;
}

input[type="checkbox"] {
    margin-left: 10px;
}
</style>