bot/urls.py
from django.urls import path
from .views_folder import unavailable_products_view, order_summary_view, tip_summary_view, table_summary_view

urlpatterns = [
    path('api/order_summary/', order_summary_view.api_order_summary, name='api_order_summary'),
    path('api/tip_summary/', tip_summary_view.api_tip_summary, name='api_tip_summary'),
    path('api/table_summary/', table_summary_view.api_table_summary, name='api_table_summary'),
    path('api/unavailable_products/', unavailable_products_view.api_unavailable_products, name='api_unavailable_products'),
]

delivery_app/urls.py
from django.urls import path
from .view.clear_solo_dept import clear_solo_debt
from .view.delivery_views import delivery_view
from .view.delivery_process import delivery_process_view
from .view.delivery_summary import delivery_summary, stas_summary
from .view.delivery_template_pdf import delivery_pdf_template_view
from .view.delivery_menu_views import delivery_menu_view, set_courier
from .view.delivery_kitchen_template_view import delivery_print_kitchen
from .view.delivery_search_view import delivery_search_view
from .view.delivery_close_cart import delivery_close_cart_view
from .view.add_delivery_customer_views import add_delivery_customer_view, save_delivery_customer_changes_view
from .view.check_delivery_customer_views import check_delivery_customer_view
from .view.for_later_delivery_view import view_for_later_delivery
from .view.future_orders_view import future_orders_view
from .view.telegram_webhook_view import telegram_webhook
from .view.recreate_order_view import recreate_order_view
from .view.delivery_costumer_view import (customer_orders_view, customer_detail_view, 
                                          order_detail_view, delete_selected_orders_view,
                                          delete_uncompleted_orders_view
                                        )
from .view.delivery_cart_views import (
    delivery_add_to_cart_view, 
    delivery_cart_view,
    delivery_increase_product_view,
    delivery_decrease_product_view,
    delivery_remove_product_view,
    delivery_empty_cart_view,
)

app_name = 'delivery_app'

urlpatterns = [
    path('delivery_process/<str:delivery_type>/', delivery_process_view, name='delivery_process'),
    path('check_delivery_number/<str:delivery_type>/', delivery_view, name='check_delivery_number'),
    path('add_delivery_customer/<str:delivery_phone_number>/<str:delivery_type>/', add_delivery_customer_view, name='add_delivery_customer'),
    path('save_delivery_customer_changes/<str:delivery_phone_number>/<str:delivery_type>/', save_delivery_customer_changes_view, {'edit': True}, name='save_delivery_customer_changes'),
    path('check_delivery_customer/<str:delivery_phone_number>/<str:delivery_type>/', check_delivery_customer_view, name='check_delivery_customer'),
    path('delivery_add_to_cart/<str:delivery_phone_number>/<str:category>/<str:delivery_type>/', delivery_add_to_cart_view, name='delivery_add_to_cart'),
    path('delivery_menu/<str:delivery_phone_number>/<str:category>/<str:delivery_type>/', delivery_menu_view, name='delivery_menu'),
    path('delivery_pdf_template/<str:delivery_phone_number>/<int:order_id>/', delivery_pdf_template_view, name='delivery_pdf_template'),
    path('delivery_close_cart/<str:delivery_phone_number>/<int:order_id>/', delivery_close_cart_view, name='delivery_close_cart'),
    path('delivery_print_kitchen/', delivery_print_kitchen, name='delivery_print_kitchen'),
    path('delivery_search/<str:delivery_phone_number>/', delivery_search_view, name='delivery_search_products'),
    path('delivery_empty_cart/<str:delivery_phone_number>/<str:delivery_type>/', delivery_empty_cart_view, name='delivery_empty_cart' ),
    path('cart/<str:delivery_phone_number>/<str:delivery_type>/', delivery_cart_view, name='delivery_cart'),
    path('cart/<str:delivery_phone_number>/<str:delivery_type>/increase/<int:product_id>/', delivery_increase_product_view, name='delivery_increase_product'),
    path('cart/<str:delivery_phone_number>/<str:delivery_type>/decrease/<int:product_id>/', delivery_decrease_product_view, name='delivery_decrease_product'),
    path('cart/<str:delivery_phone_number>/<str:delivery_type>/remove/<int:product_id>/', delivery_remove_product_view, name='delivery_remove_product'),
    path('set_courier/<str:delivery_phone_number>/<str:delivery_type>/', set_courier, name='set_courier'),
    path('clear_solo_debt/', clear_solo_debt, name='clear_solo_debt'),
    path('delivery_summary/', delivery_summary, name='delivery_summary'),
    path('later_delivery/<str:delivery_phone_number>/<str:delivery_type>/', view_for_later_delivery, name='view_for_later_delivery'),

    path('future-orders/', future_orders_view, name='future_orders'),

    path('telegram_webhook/', telegram_webhook, name='telegram_webhook'),
    path('customer-orders/', customer_orders_view, name='customer_orders'),
    path('customer/<int:customer_id>/', customer_detail_view, name='customer_detail'),
    path('delivery_order/<int:order_id>/', order_detail_view, name='order_detail'),
    path('recreate_order/<int:order_id>/', recreate_order_view, name='recreate_order'),
    path('delete_selected_orders/<int:customer_id>/', delete_selected_orders_view, name='delete_selected_orders'),
    path('delete_uncompleted_orders/<int:customer_id>/', delete_uncompleted_orders_view, name='delete_uncompleted_orders'),

    path('stas-summary/', stas_summary, name='stas_summary'),


]

delivery_app/models.py
from django.db import models
from datetime import timedelta
from django.utils import timezone
from restaurant_app.models.product import Product

# Глобальные переменные для определения выборов
CITY_CHOICES = (
    ('חיפה', 'Хайфа'), 
    ('נשר', 'Нэшер'), 
    ('טירת כרמל', 'Тира'), 
    ('כפר גלים', 'Кфар Галим'),
    ('קריית חיים', 'Кирият Хаим'), 
    ('קריית אתא', 'Кирият Ата'), 
    ('קריית ביאליק', 'Кирият Биалик'),
    ('קריית ים', 'Кирият Ям'),
    ('קריית מוצקין', 'Кирият Моцкин')
)

PAYMENT_METHOD_CHOICES = (
    ('cash', 'Наличные'),
    ('credit_card', 'Кредитная карта'),
)


class DeliveryCustomer(models.Model):
    delivery_phone_number = models.CharField(max_length=10)
    name = models.CharField(max_length=30)
    city = models.CharField(max_length=50, choices=CITY_CHOICES)
    street = models.CharField(max_length=50)
    house_number = models.CharField(max_length=10)
    floor = models.CharField(max_length=10)
    apartment_number = models.CharField(max_length=10)
    intercom_code = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.name} - {self.delivery_phone_number}"


def mark_as_completed(modeladmin, request, queryset):
    week_ago = timezone.now() - timedelta(days=7)
    queryset.filter(created_at__lte=week_ago, is_completed=False).update(is_completed=True)


class DeliveryOrder(models.Model):
    customer = models.ForeignKey(DeliveryCustomer, on_delete=models.CASCADE, related_name='orders')
    courier = models.ForeignKey('Courier', on_delete=models.SET_NULL, null=True, blank=True, related_name='orders')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_completed = models.BooleanField(default=False)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    delivery_date = models.DateField(null=True, blank=True)
    delivery_time = models.TimeField(null=True, blank=True)
    transaction_created = models.BooleanField(default=False)
    payment_method = models.CharField(
        max_length=12,
        choices=PAYMENT_METHOD_CHOICES,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = 'Delivery Order'
        verbose_name_plural = 'Delivery Orders'

    def __str__(self):
        return f"{self.pk} - {self.customer.name} ({self.customer.delivery_phone_number})"


NAME_CHOICES = [
    ('solo', 'Solo'),
    ('our_courier', 'Стас'),
    # Другие имена
]    
    
class Courier(models.Model):
    name = models.CharField(max_length=50, choices=NAME_CHOICES)  
    delivery_address = models.TextField(blank=True, null=True)
    delivery_city = models.CharField(max_length=50, choices=CITY_CHOICES, blank=True, null=True)
    delivery_amount = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    payment_method = models.CharField(max_length=12, choices=PAYMENT_METHOD_CHOICES, blank=True, null=True)

    def __str__(self):
        return self.name


class CourierDelivery(models.Model):
    courier = models.ForeignKey(Courier, on_delete=models.CASCADE)
    delivery_address = models.CharField(max_length=255)
    delivery_city = models.CharField(max_length=50, choices=CITY_CHOICES)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    payment_method = models.CharField(max_length=12, choices=PAYMENT_METHOD_CHOICES)

    def __str__(self):
        return f"{self.courier.name} - {self.delivery_city} - {self.total_price}₪"


class DeliveryProduct(models.Model):
    delivery_order = models.ForeignKey(DeliveryOrder, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    quantity = models.PositiveIntegerField(default=1)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Delivery Product'
        verbose_name_plural = 'Delivery Products'

    def __str__(self):
        return f'{self.product.product_name_rus} ({self.quantity})'


class DeliveryCart(models.Model):
    delivery_order = models.ForeignKey(DeliveryOrder, on_delete=models.CASCADE, related_name='delivery_carts', null=True)
    customer = models.ForeignKey(DeliveryCustomer, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    is_completed = models.BooleanField(default=False)

    def get_total(self):
        if not self.pk:
            return 0
        else:
            return sum([item.quantity * item.product.product_price for item in self.delivery_cart_items.all()])

    def save(self, *args, **kwargs):
        self.total_price = self.get_total()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Cart ({self.pk}) for delivery order {self.delivery_order.customer.delivery_phone_number}"


class DeliveryCartItem(models.Model):
    cart = models.ForeignKey(DeliveryCart, on_delete=models.CASCADE, related_name='delivery_cart_items')
    delivery_order = models.ForeignKey(DeliveryOrder, on_delete=models.CASCADE, related_name='delivery_cart_items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='delivery_product', null=True)
    quantity = models.PositiveIntegerField(default=1)
    printed_quantity = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        self.quantity = int(self.quantity)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.quantity} x {self.product.product_name_rus}"

delivery_app/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from datetime import datetime, time, timedelta
from django.utils.html import format_html

from .models import DeliveryCustomer


class DeliveryForm(forms.Form):
    delivery_phone_number = forms.CharField(label='Номер телефона', validators=[RegexValidator(regex=r'^\d{10}$', message='Номер телефона должен содержать ровно 10 цифр')])

class DeliveryCustomerForm(forms.ModelForm):
    city = forms.ChoiceField(choices=[('חיפה', 'Хайфа'), ('נשר', ('Нэшер')), ('טירת כרמל', 'Тира'), ('כפר גלים', 'Кфар Галим'),('קריית חיים', 'Кирият Хаим'), ('קריית אתא', 'Кирият Ата'), ('קריית ביאליק', 'Кирият Биалик'), ('קריית מוצקין', 'Кирият Моцкин'), ('קריית ים', ('Кирият Ям'))], widget=forms.Select(attrs={'class': 'form-control', 'required': True}))

    class Meta:
        model = DeliveryCustomer
        fields = ['delivery_phone_number', 'name', 'city', 'street', 'house_number', 'floor', 'apartment_number', 'intercom_code']
        widgets = {
            'delivery_phone_number': forms.TextInput(attrs={'readonly': 'readonly'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'street': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'house_number': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'floor': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'apartment_number': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'intercom_code': forms.TextInput(attrs={'class': 'form-control'}),
        }

class ProductQuantityForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=10000, initial=1, widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'style': 'width: 100px; display: inline-block;'
    }))


def generate_time_intervals(start_time, end_time, delta_minutes):
    current_time = datetime.combine(datetime.today(), start_time)
    end_datetime = datetime.combine(datetime.today(), end_time)
    time_intervals = []

    while current_time <= end_datetime:
        time_intervals.append(current_time.strftime('%H:%M'))
        current_time += timedelta(minutes=delta_minutes)

    return time_intervals

class DeliveryDateTimeForm(forms.Form):
    form_type = forms.CharField(widget=forms.HiddenInput(), initial='delivery_date_time')
    start_time = time(12, 0)
    end_time = time(22, 0)
    delta_minutes = 15

    date = forms.DateField(label='Дата', widget=forms.DateInput(attrs={'type': 'date'}))
    time_choices = generate_time_intervals(start_time, end_time, delta_minutes)
    time = forms.ChoiceField(label='Время', choices=[(time, time) for time in time_choices])

class SelectOrderForm(forms.Form):
    form_type = forms.CharField(widget=forms.HiddenInput(), initial='select_order')
    order = forms.ModelChoiceField(
        queryset=None,  # Queryset будет передан позже
        label="Выберите заказ",
        empty_label=None,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    def __init__(self, *args, **kwargs):
        orders = kwargs.pop('orders', None)
        super().__init__(*args, **kwargs)

        self.fields['order'].queryset = orders
        # Изменение отображения каждого заказа в списке
        self.fields['order'].label_from_instance = self._order_label

    def _order_label(self, order):
        # Форматирование метки для каждого заказа в списке
        return format_html(
            "{} - {} - {} - {}, {}",
            order.delivery_date.strftime('%Y-%m-%d'),
            order.customer.name,
            order.customer.delivery_phone_number,
            order.customer.street,
            order.customer.house_number
        )

delivery_app/views.py
from django.shortcuts import render

# Create your views here.

delivery_app/templates/delivery_cart.html
{% extends "base.html" %}
{% load custom_tags %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% block title %}Информация о заказе на Доставку{% endblock %}

{% block content %}
<div class="container">
    <div class="my-4"> 
        <a href="{% url 'delivery_app:delivery_menu' delivery_phone_number=delivery_phone_number category='salads' delivery_type=delivery_type %}" type="submit" class="btn btn-primary mr-3">Меню</a>

    </div>

    <h1 class="my-4" style="color: white;">Информация о заказе на Доставку</h1>
    <p style="color: white; font-size: 20px;">Номер Телефона: {{ delivery_phone_number }}</p>
    <p style="color: white; font-size: 20px;">Имя: {{ customer_name }}</p>
    <table class="table">
        <thead>
            <tr>
                <th scope="col" style="color: white; font-size: 26px;">Название</th>
                <th scope="col" style="color: white; font-size: 26px;">Количество</th>
                <th scope="col" style="color: white; font-size: 26px;">Цена</th>
                <th scope="col" style="color: white; font-size: 26px;">Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart_items %}
            <tr>
                <td style="color: rgb(231, 235, 5); text-align: center; vertical-align: middle;" >{{ item.product.product_name_rus }}</td>
                <td id="order-item-{{ item.id }}-quantity" style="color: white; text-align: center; vertical-align: middle;">{{ item.quantity|append_grams:item.product.product_name_rus }}</td>
                <td style="color: rgb(255, 255, 255); text-align: center; vertical-align: middle;">{{ item.product.product_price }}₪</td>
                <td>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn1" onclick="event.preventDefault(); document.getElementById('increase-form-{{ item.id }}').submit();">Добавить</button>
                        <form id="increase-form-{{ item.id }}" method="POST" action="{% url 'delivery_app:delivery_increase_product' delivery_phone_number=delivery_phone_number delivery_type=delivery_type product_id=item.product.id %}" style="display: none;">
                            {% csrf_token %}
                            <input type="hidden" name="product_id" value="{{ item.product.id }}">
                        </form>
                        <button type="button" class="btn1" onclick="event.preventDefault(); document.getElementById('decrease-form-{{ item.id }}').submit();">Убавить</button>
                        <form id="decrease-form-{{ item.id }}" action="{% url 'delivery_app:delivery_decrease_product' delivery_phone_number=delivery_phone_number delivery_type=delivery_type product_id=item.product.id %}" style="display: none;">
                            {% csrf_token %}
                            <input type="hidden" name="product_id" value="{{ item.product.id }}">
                        </form>
                        <button type="button" class="btn1" onclick="event.preventDefault(); document.getElementById('remove-form-{{ item.id }}').submit();">Удалить</button>
                        <form id="remove-form-{{ item.id }}" method="POST" action="{% url 'delivery_app:delivery_remove_product' delivery_phone_number=delivery_phone_number delivery_type=delivery_type product_id=item.product.id %}" style="display: none;">
                            {% csrf_token %}
                            <input type="hidden" name="product_id" value="{{ item.product.id }}">
                        </form>
                    </div>
                </td>
            </tr>        
            {% endfor %}
        </tbody>
    </table>
    
    

    <div class="text-center my-4">
        <p style="color: white;">Общая сумма: {{ cart|delivery_total_price }}₪</p>
        <form method="get" action="{% url 'delivery_app:delivery_menu' delivery_phone_number=delivery_phone_number category='delivery' delivery_type=delivery_type %}" class="d-inline-block">
            <input type="hidden" name="category" value="delivery">
            <button type="submit" class="btn btn-primary">Выбор Стоимости Доставки.</button>
        </form>        
    </div>

    <div class="payment-section mx-auto d-flex flex-column align-items-center">
        <form id="payment-form" method="post" action="{% url 'delivery_app:delivery_close_cart' delivery_phone_number=delivery_phone_number order_id=delivery_order.id %}">
            {% csrf_token %}
            <label class="form-group" style="color: rgb(238, 4, 4); font-size: 26px; text-align: center; display: block;">Метод Оплаты:</label>
            <div class="form-check mb-2">
                <input class="form-check-input" type="radio" name="payment_method" id="cash" value="cash">
                <label class="form-check-label" for="cash" style="color: rgb(238, 4, 4);">Наличные</label>
            </div>
            <div class="form-check mb-2">
                <input class="form-check-input" type="radio" name="payment_method" id="credit_card" value="credit_card">
                <label class="form-check-label" for="credit_card" style="color: rgb(238, 4, 4);">Кредитная карта</label>
            </div>
            <input type="hidden" name="courier" id="selected-courier">
            <div class="button-group mt-3">
                <button id="pay-button" type="button" class="btn2 btn-primary2 mr-2">Счет Оплачен.</button>
                <button type="button" id="delivery_print_kitchen" name="delivery_print_kitchen" class="btn-primary2 mr-2">Подтвердить Заказ.</button>
                <form hx-post="{% url 'delivery_app:delivery_pdf_template' delivery_phone_number=delivery_phone_number order_id=delivery_order.id %}" method="post">
                    {% csrf_token %}
                    <button type="button" id="print-bill" class="btn2 btn-primary2" data-phone-number="{{ delivery_phone_number }}" data-order-id="{{ delivery_order.id }}">Распечатать Счет.</button>
                </form>
            </div>
        </form>
    </div>

    <div id="courierModal" class="modal">
        <div class="modal-content" style="background-color: #1a1a1a; border: 1px solid #d4af37; color: #d4af37;">
            <span class="close" style="color: #d4af37;">&times;</span>
            <h2 style="color: #d4af37;">Выберите курьера</h2>
            <form method="POST" action="{% url 'delivery_app:set_courier' delivery_phone_number=delivery_phone_number delivery_type=delivery_type %}">
                {% csrf_token %}
                <div class="form-check" style="margin-bottom: 10px;">
                    <input class="form-check-input" type="radio" name="courier" id="our_courier" value="our_courier" style="background-color: rgba(255, 255, 255, 0.1); color: #f5e6c8; border: 1px solid #ddd; margin-right: 5px;">
                    <label class="form-check-label" for="our_courier" style="color: #d4af37;">Стас</label>
                </div>
                <div class="form-check" style="margin-bottom: 15px;">
                    <input class="form-check-input" type="radio" name="courier" id="solo" value="solo" style="background-color: rgba(255, 255, 255, 0.1); color: #f5e6c8; border: 1px solid #ddd; margin-right: 5px;">
                    <label class="form-check-label" for="solo" style="color: #d4af37;">Соло</label>
                </div>
                <button type="submit" name="set-courier-button" value="set-courier-button" class="btn btn-primary mt-2">Установить курьера</button>
            </form>
        </div>
    </div>

    <script src="https://unpkg.com/htmx.org/dist/htmx.min.js"></script>
    <script src="{% static 'scripts/delivery_cart.js' %}"></script>
    <script>
        document.getElementById('delivery_print_kitchen').addEventListener('click', function() {
            var phone = '{{ delivery_phone_number }}'; // Используйте переменную шаблона Django для номера телефона
            var orderId = '{{ delivery_order.id }}'; // Используйте переменную шаблона Django для ID заказа
            var xhr = new XMLHttpRequest();
            xhr.open('GET', '{% url "delivery_app:delivery_print_kitchen" %}?phone_number=' + phone + '&order_id=' + orderId);
            xhr.onload = function() {
                if (xhr.status === 200) {
                    var response = JSON.parse(xhr.responseText);
                    alert(response.message);
                }
            };
            xhr.send();
        });
      </script>
         
</div>
{% endblock %}

delivery_app/templates/delivery_menu.html
{% extends "base.html" %}

{% block title %}Меню на Доставку{% endblock %}

{% block content %}
<div class="container">
    <div class="mt-4">
        <a href="{% url 'delivery_app:delivery_cart' delivery_phone_number=delivery_phone_number delivery_type=delivery_type %}" type="submit" class="btn btn-primary">Корзина</a>
    </div>
    
    <h1 class="my-4" style="color: white;">Меню на Доставку №: {{ delivery_phone_number }}</h1>

    <section>
        {% include 'delivery_search.html' %}
    </section>
    
    <ul class="nav nav-tabs mb-4">
        {% for key, value in CATEGORIES.items %}
            {% if key == "soft_drinks" %}
                </ul>
                <ul class="nav nav-tabs mb-4">
            {% endif %}
            <li class="nav-item">
                <a href="{% url 'delivery_app:delivery_menu' delivery_phone_number=delivery_phone_number category=key delivery_type=delivery_type %}" class="nav-link delivery-nav-link{% if category == key %} active{% endif %}">{{ value }}</a>

            </li>
        {% endfor %}
    </ul>    

    <div id="products-container" class="row" hx-target="#products-container">
        {% for product in products %}
        <div class="col-md-3 mb-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ product.product_name_rus }}</h5>
                    <p class="card-text">{{ product.product_price }}₪</p>
                    <form action="{% url 'delivery_app:delivery_add_to_cart' delivery_phone_number=delivery_phone_number category=category delivery_type=delivery_type %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{ product.id }}">
                        {{ product_quantity_form.quantity }}
                        <button type="submit" class="btn btn-primary" {% if not product.is_available %}disabled{% endif %}>Добавить в корзину</button>
                        {% if not product.is_available %}
                            <p>Продукт закончился</p>
                        {% endif %}
                        {% if product.has_limit %}
                            <p>Осталось: {{ product.limit_quantity }}</p>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>    
    
</div>
{% endblock %}

delivery_app/templates/delivery_summary.html
{% extends "base.html" %}

{% block title %}Сводка по доставке{% endblock %}

{% block content %}
<div class="container">
    <h1 style="color: white;">Сводка по доставке</h1>
    <h3 style="color: white;">Общая сумма всех заказов: {{ all_orders_total }}₪</h3>

    <a href="{% url 'delivery_app:future_orders' %}" class="btn btn-primary">Заказы на будущее</a>

    {% if solo_cash_orders_total > 0 %}
    <div style="color: red;">
        <h3>Общая сумма заказов, оплаченных наличными Соло: {{ solo_cash_orders_total }}₪</h3>
    </div>
    {% endif %}
    
    {% if our_courier_cash_orders_total > 0 %}
    <h3 style="color: white;">Общая сумма заказов, оплаченных наличными Стасу: {{ our_courier_cash_orders_total }}₪</h3>
    <h3 style="color: white;">Сумма которую должен нам вернуть Стас: {{ our_courier_cash_orders_after_discount }}₪</h3>
    {% endif %}

    <div style="text-align: right; margin-bottom: 10px;">
        <form method="GET" action=".">
            <label for="date" style="color: white;">Выберите дату:</label>
            <input type="date" id="date" name="date" value="{{ selected_date }}">
            <input type="submit" value="Показать">
        </form>
    </div>
    
    <table class="table">
        <thead>
            <tr>
                <th style="color: white;">№</th>
                <th style="color: white;">Имя курьера</th>
                <th style="color: white;">Город доставки</th>
                <th style="color: white;">Адрес доставки</th>
                <th style="color: white;">Номер телефона</th>
                <th style="color: white;">Сумма заказа</th>
                <th style="color: white;">Метод оплаты</th>
                <th style="color: white;">Время заказа</th>
            </tr>
        </thead>        
        <tbody>
            {% for order in delivery_orders %}
            <tr>
                <td style="color: white;">{{ forloop.counter }}</td>
                <td style="color: white;">{{ order.courier.get_name_display }}</td>
                <td style="color: white;">{{ order.customer.get_city_display }}</td>
                <td style="color: white;">{{ order.customer.street }} {{ order.customer.house_number }}</td>
                <td style="color: white;">
                    <a href="{% url 'delivery_app:order_detail' order.id %}" style="color: white;">
                        {{ order.customer.delivery_phone_number }}
                    </a>
                </td>
                <td style="color: white;">{{ order.total_amount }}</td>
                <td style="color: white;">{{ order.get_payment_method_display }}</td>
                <td style="color: white;">{{ order.delivery_date }} {{ order.delivery_time|date:"H:i" }}</td>
            </tr>
            {% endfor %}
        </tbody>        
    </table>
</div>

<div class="city-orders-summary">
    <h3 style="color: white;">Заказы по городам:</h3>
    <ul>
        {% for city, data in city_order_counts %}
        <li style="color: white;">
            {{ city }}: {{ data.total_orders }}, сумма = {{ data.total_discount_amount }}
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}